<?php
/**
 * ZF2 Buch Kapitel 9
 *
 * Das Buch "Zend Framework 2 - Von den Grundlagen bis zur fertigen Anwendung"
 * von Ralf Eggert ist im Addison-Wesley Verlag erschienen.
 * ISBN 978-3-8273-2994-3
 *
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.awl.de/2994
 */

/**
 * Escaping view script
 *
 * @package    Application
 */

// prepare escape strings
$escapeHtml     = '<p onMouseOver="alert(\'XSS\');">Text</p>';
$escapeHtmlAttr = '<p width="100%">Text</p>';
$escapeJs       = 'alert(\'XSS\');';
$escapeCss      = 'body {font-size: 100px;}';
$escapeUrl      = 'http://luigis-pizza.local/pizza/show/3';
?>
<?php echo $escapeHtml . "\n"; ?>
<?php echo $this->escapeHtml($escapeHtml) . "\n";?>

<?php echo $escapeHtmlAttr . "\n"; ?>
<?php echo $this->escapeHtmlAttr($escapeHtmlAttr) . "\n";?>

<?php echo $escapeJs . "\n"; ?>
<?php echo $this->escapeJs($escapeJs) . "\n";?>

<?php echo $escapeCss . "\n"; ?>
<?php echo $this->escapeCss($escapeCss) . "\n";?>

<?php echo $escapeUrl . "\n"; ?>
<?php echo $this->escapeUrl($escapeUrl) . "\n";?>
