<?php 
/**
 * ZF2 Buch Kapitel 9
 * 
 * Das Buch "Zend Framework 2 - Das Praxisbuch"
 * von Ralf Eggert ist im Galileo-Computing Verlag erschienen. 
 * ISBN 978-3-8362-2610-3
 * 
 * @package    Pizza
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.galileocomputing.de/3460
 */

/**
 * Widget view script
 * 
 * @package    Pizza
 */

// get key
?>
<div class="hero-unit">
<h1><?php echo $this->escapeHtml($this->pizzaName); ?>!</h1>
<h3>Preis: <?php echo $this->escapeHtml($this->pizzaPrice); ?>€</h3>
<p>
Pizzaboden aus <?php echo $this->escapeHtml($this->pizzaCrust); ?>
</p>
<p>
Zutaten: 
<?php echo $this->htmlList($this->pizzaToppings); ?>
</p>
</div>
