<?php 
/**
 * ZF2 Buch Kapitel 9
 * 
 * Das Buch "Zend Framework 2 - Das Praxisbuch"
 * von Ralf Eggert ist im Galileo-Computing Verlag erschienen. 
 * ISBN 978-3-8362-2610-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.galileocomputing.de/3460
 */

/**
 * Listing 9.12 view script
 * 
 * @package    Application
 */
?>
<div class="row">
<div class="span9">
<h1>Listing 9.12</h1>
<h3><code>RandomPizza</code> View-Helper</h3>
<pre>
&lt;?php
namespace Pizza\View\Helper;

use Zend\Form\View\Helper\AbstractHelper;

class RandomPizza extends AbstractHelper
{
    protected $random = null;
    
    public function __construct($random)
    {
        $this->setRandomPizza($random);
    }
    
    public function setRandomPizza($random)
    {
        $this->random = $random;
    }
    
    public function getRandomPizza()
    {
        return $this->random;
    }
    
    public function __invoke()
    {
        $html = '&lt;div class="hero-unit"&gt;';
        $html.= '&lt;h1&gt;' . $this->getRandomPizza() . '&lt;/h1&gt;';
        $html.= '&lt;/div&gt;';
        
        return $html;
    }
}
</pre>
</div>
</div>
