<?php 
/**
 * ZF2 Buch Kapitel 9
 * 
 * Das Buch "Zend Framework 2 - Das Praxisbuch"
 * von Ralf Eggert ist im Galileo-Computing Verlag erschienen. 
 * ISBN 978-3-8362-2610-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.galileocomputing.de/3460
 */

/**
 * Listing 9.3 view script
 * 
 * @package    Application
 */
?>
<div class="row">
<div class="span9">
<h1>Listing 9.3</h1>
<h3>Einsatz von <code>ViewModel</code> in einem Action-Controller</h3>
<pre>
&lt;?php
namespace Pizza\Controller;

use Zend\Mvc\Controller\AbstractActionController;
use Zend\View\Model\ViewModel;

class IndexController extends AbstractActionController
{
    public function widgetAction()
    {
        $pizzaRow = $this->getPizzaService()->fetchSingleByRandom();
        
        return new ViewModel(array(
            'pizzaName'     => pizzaRow['name'    ],
            'pizzaPrice'    => pizzaRow['price'   ],
            'pizzaCrust'    => pizzaRow['crust'   ],
            'pizzaToppings' => pizzaRow['toppings'],
        ));
    }
}
</pre>
</div>
</div>
