<?php 
/**
 * ZF2 Buch Kapitel 9
 * 
 * Das Buch "Zend Framework 2 - Von den Grundlagen bis zur fertigen Anwendung"
 * von Ralf Eggert ist im Addison-Wesley Verlag erschienen. 
 * ISBN 978-3-8273-2994-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.awl.de/2994
 */

/**
 * Listing 9.11 view script
 * 
 * @package    Application
 */
?>
<div class="row">
<div class="span9">
<h1>Listing 9.11</h1>
<h3>Model-Service zur Auswahl einer zufälligen Pizza</h3>
<pre>
&lt;?php
namespace Pizza\Service;

class PizzaService
{
    protected $pizzaList = array(
        1 => 'Salami', 
        2 => 'Hawaii', 
        3 => 'Melone', 
        4 => 'Schinken', 
        5 => 'Thunfisch',
        6 => 'Speziale', 
        7 => 'Calzone', 
        8 => 'Vierjahreszeiten', 
        9 => 'Spinat',
    );
    
    public function fetchSingleByRandom()
    {
        $random = array_rand($this->pizzaList);

        return $this->pizzaList[$random];
    }
}
</pre>
</div>
</div>
