<?php 
/**
 * ZF2 Buch Kapitel 9
 * 
 * Das Buch "Zend Framework 2 - Das Praxisbuch"
 * von Ralf Eggert ist im Galileo-Computing Verlag erschienen. 
 * ISBN 978-3-8362-2610-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.galileocomputing.de/3460
 */

/**
 * Listing 9.5 view script
 * 
 * @package    Application
 */
?>
<div class="row">
<div class="span9">
<h1>Listing 9.5</h1>
<h3><code>start.phtml</code> View-Skript gibt <code>widget</code> Platzhalter aus</h3>
<pre>
&lt;div class="well"&gt;
&lt;h1&gt;&lt;?php echo $this-&gt;escapeHtml($this-&gt;startTitle); ?&gt;&lt;/h1&gt;
&lt;hr /&gt;
&lt;?php echo $this-&gt;widget; ?&gt;
&lt;/div&gt;
</pre>
</div>
</div>
