<?php 
/**
 * ZF2 Buch Kapitel 9
 * 
 * Das Buch "Zend Framework 2 - Das Praxisbuch"
 * von Ralf Eggert ist im Galileo-Computing Verlag erschienen. 
 * ISBN 978-3-8362-2610-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.galileocomputing.de/3460
 */

/**
 * Listing 9.4 view script
 * 
 * @package    Application
 */
?>
<div class="row">
<div class="span9">
<h1>Listing 9.4</h1>
<h3>Verschachtelter <code>ViewModel</code></h3>
<pre>
&lt;?php
use Zend\Http\PhpEnvironment\Request;
use Zend\Http\PhpEnvironment\Response;
use Zend\View\View;
use Zend\View\HelperPluginManager;
use Zend\View\Model\ViewModel;
use Zend\View\Renderer\PhpRenderer;
use Zend\View\Resolver\TemplateMapResolver;
use Zend\View\Strategy\PhpRendererStrategy;

$helpers = new HelperPluginManager();

$resolver = new TemplateMapResolver(array(
    'pizza/start'  => LUIGI_ROOT . '/module/Pizza/view/pizza/index/start.phtml',
    'pizza/widget' => LUIGI_ROOT . '/module/Pizza/view/pizza/index/widget.phtml',
));

$renderer = new PhpRenderer();
$renderer->setHelperPluginManager($helpers);
$renderer->setResolver($resolver);

$request  = new Request();
$response = new Response();

$widgetModel = new ViewModel();
$widgetModel->setTemplate('pizza/widget');
$widgetModel->setVariables(array(
    'pizzaName'     => 'Pizza Salami',
    'pizzaPrice'    => 6.95,
    'pizzaCrust'    => 'Weizenmehl',
    'pizzaToppings' => array(
        'Salami',
        'Tomatenpampe',
        'Käse',
    ),
));

$startModel = new ViewModel();
$startModel->setTemplate('pizza/start');
$startModel->setVariables(array(
    'startTitle' => 'Luigis Pizza-Service',
));
$startModel->addChild($widgetModel, 'widget');

$view = new View();
$view->setRequest($request);
$view->setResponse($response);
$view->getEventManager()->attach(new PhpRendererStrategy($renderer));
$view->render($startModel);

echo $view->getResponse()->getContent();
</pre>
<h3>Ausgabe</h3>
<?php 
use Zend\Http\PhpEnvironment\Request;
use Zend\Http\PhpEnvironment\Response;
use Zend\View\View;
use Zend\View\HelperPluginManager;
use Zend\View\Model\ViewModel;
use Zend\View\Renderer\PhpRenderer;
use Zend\View\Resolver\TemplateMapResolver;
use Zend\View\Strategy\PhpRendererStrategy;

$helpers = new HelperPluginManager();

$resolver = new TemplateMapResolver(array(
    'pizza/start'  => LUIGI_ROOT . '/module/Pizza/view/pizza/index/start.phtml',
    'pizza/widget' => LUIGI_ROOT . '/module/Pizza/view/pizza/index/widget.phtml',
));

$renderer = new PhpRenderer();
$renderer->setHelperPluginManager($helpers);
$renderer->setResolver($resolver);

$request  = new Request();
$response = new Response();

$widgetModel = new ViewModel();
$widgetModel->setTemplate('pizza/widget');
$widgetModel->setVariables(array(
    'pizzaName'     => 'Pizza Salami',
    'pizzaPrice'    => 6.95,
    'pizzaCrust'    => 'Weizenmehl',
    'pizzaToppings' => array(
        'Salami',
        'Tomatenpampe',
        'Käse',
    ),
));

$startModel = new ViewModel();
$startModel->setTemplate('pizza/start');
$startModel->setVariables(array(
    'startTitle' => 'Luigis Pizza-Service',
));
$startModel->addChild($widgetModel, 'widget');

$view = new View();
$view->setRequest($request);
$view->setResponse($response);
$view->getEventManager()->attach(new PhpRendererStrategy($renderer));
$view->render($startModel);

echo $view->getResponse()->getContent();
?>
</div>
</div>
