<?php 
/**
 * ZF2 Buch Kapitel 9
 * 
 * Das Buch "Zend Framework 2 - Von den Grundlagen bis zur fertigen Anwendung"
 * von Ralf Eggert ist im Addison-Wesley Verlag erschienen. 
 * ISBN 978-3-8273-2994-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.awl.de/2994
 */

/**
 * Index view script
 * 
 * @package    Application
 */
?>
<h1>Listings - Kapitel 9</h1>
<table class="table table-bordered table-striped table-hover table-condensed">
<thead>
<tr>
<th>Listing</th>
<th>Beschreibung</th>
</tr>
</thead>
<tbody>
<tr>
<td><a href="/listing/listing0901">Listing 9.1</a></td>
<td>Zusammenspiel der Teilkomponenten von <code>Zend\View</code></td>
</tr>
<tr>
<td><a href="/listing/listing0902">Listing 9.2</a></td>
<td>Konfiguration des View-Managers für <code>Application</code> Modul</td>
</tr>
<tr>
<td><a href="/listing/listing0903">Listing 9.3</a></td>
<td>Einsatz von <code>ViewModel</code> in einem Action-Controller</td>
</tr>
<tr>
<td><a href="/listing/listing0904">Listing 9.4</a></td>
<td>Verschachtelter <code>ViewModel</code></td>
</tr>
<tr>
<td><a href="/listing/listing0905">Listing 9.5</a></td>
<td><code>start.phtml</code> View-Skript gibt <code>widget</code> Platzhalter aus</td>
</tr>
<tr>
<td><a href="/listing/listing0906">Listing 9.6</a></td>
<td>Modul-Klasse registriert <code>JsonStrategy</code> für ausgewählte Controller</td>
</tr>
<tr>
<td><a href="/listing/listing0907">Listing 9.7</a></td>
<td>Controller der JSON Daten ausgeben soll</td>
</tr>
<tr>
<td><a href="/listing/listing0908">Listing 9.8</a></td>
<td>Beispiel für ein View-Skript</td>
</tr>
<tr>
<td><a href="/listing/listing0909">Listing 9.9</a></td>
<td>View-Skript verwendet View-Helper für HTML-Kopfdaten</td>
</tr>
<tr>
<td><a href="/listing/listing0910">Listing 9.10</a></td>
<td>View-Skript verwendet View-Helper für Escaping</td>
</tr>
<tr>
<td><a href="/listing/listing0911">Listing 9.11</a></td>
<td>Model-Service zur Auswahl einer zufälligen Pizza</td>
</tr>
<tr>
<td><a href="/listing/listing0912">Listing 9.12</a></td>
<td><code>RandomPizza</code> View-Helper</td>
</tr>
<tr>
<td><a href="/listing/listing0913">Listing 9.13</a></td>
<td>Factory-Klasse für <code>RandomPizza</code> View Helper</td>
</tr>
<tr>
<td><a href="/listing/listing0914">Listing 9.14</a></td>
<td>Modul-Klasse zur Konfiguration des <code>RandomPizza</code> View-Helpers</td>
</tr>
<tr>
<td><a href="/listing/listing0915">Listing 9.15</a></td>
<td>Einsatz des <code>RandomPizza</code> View Helpers</td>
</tr>
</tbody>
</table>
